### ISSUE TITLE
Harden segment/point ID generation

### ISSUE THREAD

**Issue by oncletom** [bbcrd/peaks.js#110]
Possible solutions:

- `cuid` (safer)
- Date + Math.random() (smaller)

**Comment by agtilden** [comment]
Why not let the user provide point ids during creation? I'd like to have this so I can correlate points in my own pointDragEndHandler. In addition it would be convenient to have a removeByID method for the points api instead of just removeByTime and removeAll. In my case my "points" already have uuids from another source -- this works for now in the event handler since the same point object i pass in is given back but there doesn't appear to be any guarantee that this will remain the case.

**Comment by oncletom** [comment]
@agtilden we could definitely do it. That's something to do as part of #6

**Comment by chrisn** [comment]
Resolved via #141.
